import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'package:mandi/core/theme/app_theme.dart';
import 'package:mandi/data/models/product_model.dart';
import 'package:mandi/providers/shop_context_provider.dart';
import 'package:mandi/modules/products/providers/product_provider.dart';

class AddEditProductPage extends StatefulWidget {
  final Product? product;

  const AddEditProductPage({super.key, this.product});

  @override
  State<AddEditProductPage> createState() => _AddEditProductPageState();
}

class _AddEditProductPageState extends State<AddEditProductPage> {
  final _formKey = GlobalKey<FormState>();
  late final TextEditingController _name;
  late final TextEditingController _category;
  late final TextEditingController _pricePer40kg;
  late final TextEditingController _currentStockKg;
  late final TextEditingController _minStockKg;
  late final TextEditingController _description;
  bool _saving = false;

  bool get _isEditing => widget.product != null;

  @override
  void initState() {
    super.initState();
    final p = widget.product;
    _name = TextEditingController(text: p?.name ?? '');
    _category = TextEditingController(text: p?.category ?? 'Grains');
    _pricePer40kg = TextEditingController(
        text: p != null ? p.sellingPrice.toStringAsFixed(0) : '');
    _currentStockKg = TextEditingController(
        text: p != null ? p.currentStock.toStringAsFixed(0) : '0');
    _minStockKg = TextEditingController(
        text: p != null ? p.minStockLevel.toStringAsFixed(0) : '400');
    _description = TextEditingController(text: p?.description ?? '');
  }

  @override
  void dispose() {
    _name.dispose();
    _category.dispose();
    _pricePer40kg.dispose();
    _currentStockKg.dispose();
    _minStockKg.dispose();
    _description.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    final shopId = context.read<ShopContextProvider>().currentShopId!;
    final provider = context.read<ProductProvider>();
    setState(() => _saving = true);

    try {
      final price = double.tryParse(_pricePer40kg.text.trim()) ?? 0;
      final stock = double.tryParse(_currentStockKg.text.trim()) ?? 0;
      final minStock = double.tryParse(_minStockKg.text.trim()) ?? 0;

      if (_isEditing) {
        final updated = widget.product!.copyWith(
          name: _name.text.trim(),
          category: _category.text.trim(),
          sellingPrice: price,
          currentStock: stock,
          minStockLevel: minStock,
          description: _description.text.trim(),
        );
        await provider.updateProduct(updated);
      } else {
        final newProduct = Product(
          id: '', // Generated by Postgres
          shopId: shopId,
          name: _name.text.trim(),
          category: _category.text.trim(),
          unit: '40 KG (Maund)',
          weightPerUnitKg: 40,
          sellingPrice: price,
          currentStock: stock,
          minStockLevel: minStock,
          description: _description.text.trim(),
        );
        await provider.addProduct(newProduct);
      }

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
            content: Text(
                _isEditing ? 'Product updated.' : 'Product added successfully.')),
      );
      Navigator.pop(context);
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(e.toString()), backgroundColor: MColors.danger),
      );
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(_isEditing ? 'Edit Product' : 'Add Product'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(MSpacing.lg),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              TextFormField(
                controller: _name,
                decoration: const InputDecoration(
                  labelText: 'Product Name *',
                  hintText: 'e.g. Super Basmati Rice / Wheat',
                ),
                validator: (v) =>
                    (v == null || v.trim().isEmpty) ? 'Required' : null,
              ),
              const SizedBox(height: MSpacing.md),
              TextFormField(
                controller: _category,
                decoration: const InputDecoration(
                  labelText: 'Category',
                  hintText: 'e.g. Rice, Wheat, Pulses',
                ),
              ),
              const SizedBox(height: MSpacing.md),
              TextFormField(
                controller: _pricePer40kg,
                keyboardType:
                    const TextInputType.numberWithOptions(decimal: true),
                decoration: const InputDecoration(
                  labelText: 'Selling Price per 40 KG / Maund (PKR) *',
                  hintText: 'e.g. 5200',
                  suffixText: 'PKR / 40kg',
                ),
                validator: (v) =>
                    (v == null || v.trim().isEmpty) ? 'Required' : null,
              ),
              const SizedBox(height: MSpacing.md),
              TextFormField(
                controller: _currentStockKg,
                keyboardType:
                    const TextInputType.numberWithOptions(decimal: true),
                decoration: const InputDecoration(
                  labelText: 'Current Stock (KG) *',
                  hintText: 'e.g. 1200 (1200 KG = 30 Maund)',
                  suffixText: 'KG',
                ),
                validator: (v) =>
                    (v == null || v.trim().isEmpty) ? 'Required' : null,
              ),
              const SizedBox(height: MSpacing.md),
              TextFormField(
                controller: _minStockKg,
                keyboardType:
                    const TextInputType.numberWithOptions(decimal: true),
                decoration: const InputDecoration(
                  labelText: 'Low Stock Alert Level (KG)',
                  hintText: 'e.g. 400 KG (Triggers red alert when below 10 Maund)',
                  suffixText: 'KG',
                ),
              ),
              const SizedBox(height: MSpacing.md),
              TextFormField(
                controller: _description,
                maxLines: 2,
                decoration: const InputDecoration(
                  labelText: 'Description / Notes',
                  hintText: 'Optional quality notes or grain variety',
                ),
              ),
              const SizedBox(height: MSpacing.xl),
              ElevatedButton(
                onPressed: _saving ? null : _submit,
                child: _saving
                    ? const SizedBox(
                        width: 20,
                        height: 20,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          color: Colors.white,
                        ),
                      )
                    : Text(_isEditing ? 'Save Changes' : 'Add Product'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
